### ISSUE TITLE
Full stack hello world example fails

### ISSUE THREAD

**Issue by jjr2527** [onejs/one#119]
Started with npx one and followed the hello-world example but received the following
```
➜  hello-world git:(main) ✗ pnpm run dev

> hello-world@1.1.294 dev /Users/jjr2527/source/oneframework/hello-world
> one dev


    ➡ [tamagui] built config and components (472ms)
[vite] connected.
11:14:53 AM [vite] (ssr) warning: rewrote react-native-safe-area-context to @vxrn/safe-area but was not an abolute path and was not handled by other plugins. This will lead to duplicated modules for the same path. To avoid duplicating modules, you should resolve to an absolute path.
  Plugin: alias
Error: The following dependencies are imported but could not be resolved:

  @tamagui/core/reset.css (imported by /Users/jjr2527/source/oneframework/hello-world/app/_layout.tsx)
  @tamagui/core (imported by /Users/jjr2527/source/oneframework/hello-world/code/theme/ToggleThemeButton.tsx)

Are they installed?
    at file:///Users/jjr2527/source/oneframework/hello-world/node_modules/.pnpm/vite@6.0.0-beta.1_@types+node@22.7.4_lightningcss@1.27.0_terser@5.34.1/node_modules/vite/dist/node/chunks/dep-BZ_CwQkz.js:37640:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/jjr2527/source/oneframework/hello-world/node_modules/.pnpm/vite@6.0.0-beta.1_@types+node@22.7.4_lightningcss@1.27.0_terser@5.34.1/node_modules/vite/dist/node/chunks/dep-BZ_CwQkz.js:66107:28
✘ [ERROR] Could not read from file: /Users/jjr2527/source/oneframework/hello-world/@vxrn/safe-area

    node_modules/.pnpm/one@1.1.294_@swc+helpers@0.5.13_@types+node@22.7.4_expo@51.0.36_@babel+core@7.25.7_@babel+pre_5ewaf5bzplclga4vion3quuqau/node_modules/one/dist/esm/index.mjs:6:29:
      6 │ import { SafeAreaView } from "react-native-safe-area-context";
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

11:14:54 AM [vite] (ssr) warning: rewrote react-native-safe-area-context to @vxrn/safe-area but was not an abolute path and was not handled by other plugins. This will lead to duplicated modules for the same path. To avoid duplicating modules, you should resolve to an absolute path.
  Plugin: alias
11:14:54 AM [vite] (ssr) warning: rewrote react-native-safe-area-context to @vxrn/safe-area but was not an abolute path and was not handled by other plugins. This will lead to duplicated modules for the same path. To avoid duplicating modules, you should resolve to an absolute path.
  Plugin: alias
11:14:54 AM [vite] (ssr) warning: rewrote react-native-safe-area-context to @vxrn/safe-area but was not an abolute path and was not handled by other plugins. This will lead to duplicated modules for the same path. To avoid duplicating modules, you should resolve to an absolute path.
  Plugin: alias
11:14:54 AM [vite] (ssr) warning: rewrote react-native-safe-area-context to @vxrn/safe-area but was not an abolute path and was not handled by other plugins. This will lead to duplicated modules for the same path. To avoid duplicating modules, you should resolve to an absolute path.
  Plugin: alias
11:14:54 AM [vite] (ssr) warning: rewrote react-native-safe-area-context to @vxrn/safe-area but was not an abolute path and was not handled by other plugins. This will lead to duplicated modules for the same path. To avoid duplicating modules, you should resolve to an absolute path.
  Plugin: alias
11:14:54 AM [vite] (ssr) warning: rewrote react-native-safe-area-context to @vxrn/safe-area but was not an abolute path and was not handled by other plugins. This will lead to duplicated modules for the same path. To avoid duplicating modules, you should resolve to an absolute path.
  Plugin: alias
11:14:54 AM [vite] (ssr) warning: rewrote react-native-safe-area-context to @vxrn/safe-area but was not an abolute path and was not handled by other plugins. This will lead to duplicated modules for the same path. To avoid duplicating modules, you should resolve to an absolute path.
  Plugin: alias

 ERROR  Build failed with 1 error:                                 11:14:54 AM
node_modules/.pnpm/one@1.1.294_@swc+helpers@0.5.13_@types+node@22.7.4_expo@51.0.36_@babel+core@7.25.7_@babel+pre_5ewaf5bzplclga4vion3quuqau/node_modules/one/dist/esm/index.mjs:6:29: ERROR: Could not read from file: /Users/jjr2527/source/oneframework/hello-world/@vxrn/safe-area

  node_modules/.pnpm/one@1.1.294_@swc+helpers@0.5.13_@types+node@22.7.4_expo@51.0.36_@babel+core@7.25.7_@babel+pre_5ewaf5bzplclga4vion3quuqau/node_modules/one/dist/esm/index.mjs:6:29: ERROR: Could not read from file: @vxrn/safe-area
  at failureErrorWithLog (node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1472:15)
  at node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:945:25
  at node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1353:9
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)



 ERROR  Build failed with 1 error:                                 11:14:54 AM
node_modules/.pnpm/one@1.1.294_@swc+helpers@0.5.13_@types+node@22.7.4_expo@51.0.36_@babel+core@7.25.7_@babel+pre_5ewaf5bzplclga4vion3quuqau/node_modules/one/dist/esm/index.mjs:6:29: ERROR: Could not read from file: /Users/jjr2527/source/oneframework/hello-world/@vxrn/safe-area

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by wesbos** [comment]
Also hitting this, seems like the one vite plugin is re-writing some deps and it doesnt work well with pnpm.

running with npm works fine

**Comment by natew** [comment]
Hey Wes, yes I think we need to disable pnpm or at least configure it properly for now.

We need to add the caveat that this doesn't work (yet) with symlinked node_modules. Will get that in today. If you try doing hardlinked strategy with pnpm I think it'll work, I'll give it a test here in a bit.

**Comment by natew** [comment]
This should be fixed in 1.1.295, tested just now and it patches.
