### ISSUE TITLE
React is not defined

### ISSUE THREAD

**Issue by clayrisser** [onejs/one#134]
I get the error `React is not defined` from the tamagui compiler when it's building my code in onejs. I removed all the `import React from 'react'` imports and switch the tsconfig to `"jsx": "react-jsx"`.

```
    ➡ [tamagui] built config and components (395ms)
Tamagui failed loading "/Users/clayrisser/Projects/.bitspur/multiplatform.one/platforms/one/.tamagui/multiplatformonecomponents-components.config.cjs"
  
  React is not defined
  ReferenceError: React is not defined
    at Object.<anonymous> (/Users/clayrisser/Projects/.bitspur/multiplatform.one/platforms/one/.tamagui/multiplatformonecomponents-components.config.cjs:220414:19)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at newLoader (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/esbuild-register/dist/node.js:2262:9)
    at newLoader (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/esbuild-register/dist/node.js:2262:9)
    at Object.newLoader (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/esbuild-register/dist/node.js:2262:9)
    at extensions..js (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/esbuild-register/dist/node.js:4833:24)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at Module.tamaguiRequire [as require] (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/static/dist/registerRequire.js:66:17)
    at require (node:internal/modules/cjs/helpers:119:18)
    at attemptLoad (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/static/dist/extractor/bundleConfig.js:223:30)
    at /Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/static/dist/extractor/bundleConfig.js:238:21
    at Array.flatMap (<anonymous>)
    at loadComponentsInner (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/static/dist/extractor/bundleConfig.js:205:36)
    at loadComponents (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/static/dist/extractor/bundleConfig.js:180:70)
    at bundleConfig (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/static/dist/extractor/bundleConfig.js:142:22)
    at async getBundledConfig (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/static/dist/extractor/bundleConfig.js:66:12)
    at async loadTamagui (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/static/dist/extractor/loadTamagui.js:50:59)
    at async Object.load [as loadTamagui] (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/static/dist/extractor/createExtractor.js:70:60)
    at async loadTamaguiBuildConfig (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/vite-plugin/dist/esm/loadTamagui.mjs:22:19)
    at async load (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/vite-plugin/dist/esm/plugin.mjs:18:34)
    at async config (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/vite-plugin/dist/esm/plugin.mjs:45:11)
    at async runConfigHook (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/vite/dist/node/chunks/dep-BZ_CwQkz.js:68197:19)
    at async resolveConfig (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/vite/dist/node/chunks/dep-BZ_CwQkz.js:67589:12)
    at async _createServer (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/vite/dist/node/chunks/dep-BZ_CwQkz.js:58281:18)
    at async dev (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/vxrn/dist/exports/dev.mjs:30:20)
    at async run (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/one/dist/esm/cli/run.mjs:9:9)
    at async Object.run (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/one/dist/esm/cli.mjs:30:7)
    at async runCommand (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/citty/dist/index.mjs:316:16)
    at async runCommand (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/citty/dist/index.mjs:307:11)
    at async runMain (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/citty/dist/index.mjs:445:7)

  
Tamagui failed loading "/Users/clayrisser/Projects/.bitspur/multiplatform.one/platforms/one/.tamagui/ui-components.config.cjs"
  
  React is not defined
  ReferenceError: React is not defined
    at Object.<anonymous> (/Users/clayrisser/Projects/.bitspur/multiplatform.one/platforms/one/.tamagui/ui-components.config.cjs:225193:19)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at newLoader (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/esbuild-register/dist/node.js:2262:9)
    at newLoader (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/esbuild-register/dist/node.js:2262:9)
    at Object.newLoader (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/esbuild-register/dist/node.js:2262:9)
    at extensions..js (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/esbuild-register/dist/node.js:4833:24)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at Module.tamaguiRequire [as require] (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/static/dist/registerRequire.js:66:17)
    at require (node:internal/modules/cjs/helpers:119:18)
    at attemptLoad (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/static/dist/extractor/bundleConfig.js:223:30)
    at /Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/static/dist/extractor/bundleConfig.js:238:21
    at Array.flatMap (<anonymous>)
    at loadComponentsInner (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/static/dist/extractor/bundleConfig.js:205:36)
    at loadComponents (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/static/dist/extractor/bundleConfig.js:180:70)
    at bundleConfig (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/static/dist/extractor/bundleConfig.js:142:22)
    at async getBundledConfig (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/static/dist/extractor/bundleConfig.js:66:12)
    at async loadTamagui (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/static/dist/extractor/loadTamagui.js:50:59)
    at async Object.load [as loadTamagui] (/Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/static/dist/extractor/createExtractor.js:70:60)
    at async loadTamaguiBuildConfig (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/vite-plugin/dist/esm/loadTamagui.mjs:22:19)
    at async load (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/vite-plugin/dist/esm/plugin.mjs:18:34)
    at async config (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/@tamagui/vite-plugin/dist/esm/plugin.mjs:45:11)
    at async runConfigHook (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/vite/dist/node/chunks/dep-BZ_CwQkz.js:68197:19)
    at async resolveConfig (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/vite/dist/node/chunks/dep-BZ_CwQkz.js:67589:12)
    at async _createServer (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/vite/dist/node/chunks/dep-BZ_CwQkz.js:58281:18)
    at async dev (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/vxrn/dist/exports/dev.mjs:30:20)
    at async run (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/one/dist/esm/cli/run.mjs:9:9)
    at async Object.run (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/one/dist/esm/cli.mjs:30:7)
    at async runCommand (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/citty/dist/index.mjs:316:16)
    at async runCommand (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/citty/dist/index.mjs:307:11)
    at async runMain (file:///Users/clayrisser/Projects/.bitspur/multiplatform.one/node_modules/citty/dist/index.mjs:445:7)
```

**Comment by clayrisser** [comment]
For more context, I built my components using `tamagui-build` and then I added the components package to the tamagui compiler when running vite. Is it a problem that it's getting processed twice?

**Comment by clayrisser** [comment]
Perhaps this issue is more of a tamagui issue instead of an issue with onejs. I noticed I'm getting the following error when running `tamagui-build`.

```
'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
```

Seems odd because I thought I don't need to import React if I'm using `"jsx": "react-jsx"`

**Comment by clayrisser** [comment]
I found my issue. I believe I was barking up the wrong tree. When I removed my React imports, there was some code that was referencing react directly that I missed, for example `React.useEffect` etc...
