### ISSUE TITLE
Error running "fullstack" example - SSR error while loading file ./(feed)/index.tsx

### ISSUE THREAD

**Issue by janek** [onejs/one#215]
I'm using bun and node 22.

I did:
- `bunx one`
- chose the fullstack (drizzle etc) example
- cd `hello-world`, `bun dev`

The project doesn't work and I'm getting:
```
SSR error while loading file ./(feed)/index.tsx from URL http://localhost:8081/
 Error: Failed to fetch feed: 
    at Module.loader (/Users/janek/Developer/temp/onestack-test/hello-world/app/(feed)/index.tsx:48:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.handleSSR (file:///Users/janek/Developer/temp/onestack-test/hello-world/node_modules/one/dist/esm/vite/createFileSystemRouter.mjs:49:26)
    at async Object.handler (file:///Users/janek/Developer/temp/onestack-test/hello-world/node_modules/one/dist/esm/createHandleRequest.mjs:93:33)
    at async file:///Users/janek/Developer/temp/onestack-test/hello-world/node_modules/one/dist/esm/vite/createFileSystemRouter.mjs:168:27
Error rendering / on server
 Failed to fetch feed: 

Error: Failed to fetch feed: 
    at Module.loader (/Users/janek/Developer/temp/onestack-test/hello-world/app/(feed)/index.tsx:48:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.handleSSR (file:///Users/janek/Developer/temp/onestack-test/hello-world/node_modules/one/dist/esm/vite/createFileSystemRouter.mjs:49:26)
    at async Object.handler (file:///Users/janek/Developer/temp/onestack-test/hello-world/node_modules/one/dist/esm/createHandleRequest.mjs:93:33)
    at async file:///Users/janek/Developer/temp/onestack-test/hello-world/node_modules/one/dist/esm/vite/createFileSystemRouter.mjs:168:27

```

**Comment by zetavg** [comment]
Hi! Maybe worth checking if the PostgreSQL database (`DATABASE_URL` in your `.env`) is up and running?

**Comment by janek** [comment]
hi! it wasn't - I probably should have thought about that. Thank you for the help and the quick response
