### ISSUE TITLE
cannot build in docker ci

### ISSUE THREAD

**Issue by prabirshrestha** [onejs/one#240]
I'm getting the following error when building in x86 docker in CI. When building in Mac ARM or Linux ARM VM I don't seem to have issue. It is just a hello world one app that only run `pnpm build:web`. I don't need to support building iOS/android in CI but only on my Mac.

```
▪▪▪▪ app:build (c5fe6d67)
app:build | > app@1.1.330 build:web /_work/objstor-runner/objstor/objstor/apps/app
app:build | > one build
app:build | ⚠️ No ONE_SERVER_URL environment set, set it in your .env to your target deploy URL
app:build |  🩹 Patching rollup
app:build |  🩹 Patching react
app:build |  🩹 Patching @react-native/assets-registry
app:build |  🩹 Patching @react-native-masked-view/masked-view
app:build |  🩹 Patching expo
app:build |  🩹 Patching @expo/vector-icons
app:build |  🩹 Patching @react-native-community/cli-config
app:build |  🩹 Patching react-dom
app:build |  🩹 Patching @hono/node-server
app:build |  🔨 build client
app:build | 
app:build |     ➡ [tamagui] built config and components (562ms)
app:build | vite v6.0.0-beta.1 building for production...
app:build | transforming...
app:build |  web  |                     index   ·    2 found   ·    2 opt   ·    2 flat    12ms 
app:build |  web  |         ToggleThemeButton   ·    1 found   ·    1 opt   ·    1 flat     6ms 
app:build | [plugin:vite:resolve] [plugin vite:resolve] Module "crypto" has been externalized for browser compatibility, imported by "/_work/objstor-runner/objstor/objstor/node_modules/expo-modules-core/build/uuid/uuid.web.js". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
app:build | ../../node_modules/one/dist/esm/useLoader.mjs (51:27): Use of eval in "../../node_modules/one/dist/esm/useLoader.mjs" is strongly discouraged as it poses security risks and may cause issues with minification.
app:build | ✓ 3452 modules transformed.
app:build | rendering chunks...
app:build | computing gzip size...
app:build | dist/client/.vite/manifest.json                      1.12 kB │ gzip:   0.34 kB
app:build | (!) Some chunks are larger than 500 kB after minification. Consider:
app:build | dist/client/.vite/ssr-manifest.json                101.61 kB │ gzip:   8.09 kB
app:build | - Using dynamic import() to code-split the application
app:build | dist/client/assets/app-icon-DXK4YC68.png           121.82 kB
app:build | - Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
app:build | dist/client/assets/index-Bh3ce6i7.css                0.97 kB │ gzip:   0.43 kB
app:build | - Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
app:build | dist/client/assets/_layout-Cr6ZBQrF.css             13.39 kB │ gzip:   2.98 kB
app:build | dist/client/assets/index-DPcCkUnq.js                11.96 kB │ gzip:   4.57 kB
app:build | dist/client/assets/index-wpsE7qmM.js                85.54 kB │ gzip:  32.47 kB
app:build | dist/client/assets/_layout-CrTxLhSm.js             179.09 kB │ gzip:  62.79 kB
app:build | dist/client/assets/_virtual_one-entry-CdvIG_UX.js  617.51 kB │ gzip: 192.98 kB
app:build | ✓ built in 7.40s
app:build |  🔨 build server
app:build | vite v6.0.0-beta.1 building SSR bundle for production...
app:build | transforming...
app:build |  web  |                     index   ·    2 found   ·    2 opt   ·    2 flat     4ms 
app:build |  web  |         ToggleThemeButton   ·    1 found   ·    1 opt   ·    1 flat     9ms 
app:build | x Build failed in 3.40s
Error: app:build | [error] [vite:load-fallback] Could not load /_work/objstor-runner/objstor/objstor/node_modules/react-native-web/dist/cjs/index.js/Libraries/Utilities/codegenNativeComponent (imported by ../../node_modules/react-native-screens/lib/module/fabric/ScreenContainerNativeComponent.js): ENOTDIR: not a directory, open '/_work/objstor-runner/objstor/objstor/node_modules/react-native-web/dist/cjs/index.js/Libraries/Utilities/codegenNativeComponent'
app:build |   at async open (node:internal/fs/promises:639:25)
app:build |   at async Object.readFile (node:internal/fs/promises:1239:14)
app:build |   at async Object.load (/_work/objstor-runner/objstor/objstor/node_modules/vite/dist/node/chunks/dep-BZ_CwQkz.js:64968:25)
app:build |   at async PluginDriver.hookFirstAndGetPlugin (/_work/objstor-runner/objstor/objstor/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:20707:28)
app:build |   at async /_work/objstor-runner/objstor/objstor/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:19827:33
app:build |   at async Queue.work (/_work/objstor-runner/objstor/objstor/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:20917:32) 
app:build | ✓ 2843 modules transformed.
Error: app:build | [error] [vite:load-fallback] Could not load /_work/objstor-runner/objstor/objstor/node_modules/react-native-web/dist/cjs/index.js/Libraries/Utilities/codegenNativeComponent (imported by ../../node_modules/react-native-screens/lib/module/fabric/ScreenContainerNativeComponent.js): ENOTDIR: not a directory, open '/_work/objstor-runner/objstor/objstor/node_modules/react-native-web/dist/cjs/index.js/Libraries/Utilities/codegenNativeComponent'
app:build |  ELIFECYCLE  Command failed with exit code 1.
▪▪▪▪ app:build (15s 547ms, c5fe6d67)
Error: task_runner::run_failed
  × Task app:build failed to run.
  ╰─▶ Process pnpm failed: exit code 1
Error: Process completed with exit code 1.
```

**Comment by zetavg** [comment]
Thanks for reporting this interesting one!

Hmm, I tried on DigitalOcean VPS but did not see this issue. Using Tamagui Minimal template, one `1.1.330`.

I'll try a different node version and also on GitHub Actions later today. Suspecting the node version or the Docker environment is causing some differences.

![](https://github.com/user-attachments/assets/087372fb-860e-40cb-b5bb-f90dc6ee8dd8)

```bash
$ uname -a
Linux testing-ubuntu-s-1vcpu-2gb-sgp1-01 6.8.0-36-generic #36-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun 10 10:49:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by prabirshrestha** [comment]
I use this for running custom GitHub actions runner in a vps.

```bash
docker run -d --restart always --name github-runner-myrepo \
  -e REPO_URL="https://github.com/username/myrepo" \
  -e RUNNER_NAME="myrepo-runner" \
  -e RUNNER_TOKEN="__REPLACE_ME__" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  myoung34/github-runner:latest
```

I use proto for setting up my tools. https://moonrepo.dev/proto

**Comment by prabirshrestha** [comment]
Finally found the root cause which is the same as https://github.com/onejs/one/issues/195#issuecomment-2466501028. On Mac I had the folder renamed to it worked, but the GitHub repo still had it named starting with `obj`, renamed the GitHub project and I was able to finally build in the CI.

Not sure why a path containing `obj` fails but this is most likely some languages treats it as object files.

**Comment by zetavg** [comment]
Nice, glad that the cause is now identified
