### ISSUE TITLE
Animation breaks the build

### ISSUE THREAD

**Issue by ofersadgat** [onejs/one#242]
As soon as I add animation properties, the build breaks with the following error:

```
 TypeError: Cannot read properties of null (reading 'useEffect')
    at useEffect (/Users/Code/test/node_modules/react/cjs/react.development.js:1634:21)
    at useAnimations (/Users/Code/test/node_modules/@tamagui/animations-css/src/createAnimations.tsx:70:7
```

repro:

install:
npx one -> minimal tamagui ->

change index.tsx:

```tsx
function AnimatedText(props: {strings: string[]}){
  const {strings} = props;
  const [textIndex, setTextIndex] = React.useState(0);
  useEffect(() => {
    const interval = setTimeout(() => {
      setTextIndex((textIndex + 1) % strings.length);
    }, 5000);
    return () => {
      clearTimeout(interval);
    };
  }, [textIndex]);
  return <Text
              animation='200ms'
              animateOnly={['transform', 'opacity']}
              opacity={1}
              enterStyle={{
                opacity: 0,
              }}
              exitStyle={{
                opacity: 0,
              }}
              >
            {strings[textIndex]}
          </Text>;
}

export function HomePage() {
  return (
    <YStack bg="$color1" mih="100%" gap="$4" ai="center" jc="center" f={1}>
      <Text fontSize={20}>Hello, world</Text>
      <AnimatedText strings={['this', 'is', 'a', 'test']} />
      <Image src={oneBall} width={128} height={128} />
      <ToggleThemeButton />
    </YStack>
  )
}```

**Comment by natew** [comment]
Had to add the missing dependency, pushed that update to the template now, thanks for the heads up.
