### ISSUE TITLE
Fullstack installation fails on macOS with yarn

### ISSUE THREAD

**Issue by brandondrew** [onejs/one#263]
# TLDR: #

*Yarn:* 4.5.2
*nvm:* 0.40.1
*macOS:* 14.7 (23H124)
*zsh:* 5.9 (x86_64-apple-darwin23.0)
*Template*: Fullstack - Drizzle, Postgres, Tamagui, Biome

This should tell the whole story:

```shell

brandon@Air JavaScript % npx one@latest
Need to install the following packages:
one@1.1.334
Ok to proceed? (y) 

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
npm warn deprecated @babel/plugin-proposal-optional-catch-binding@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
npm warn deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm warn deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm warn deprecated rimraf@2.6.3: Rimraf versions prior to v4 are no longer supported
npm warn deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm warn deprecated @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
npm warn deprecated glob@7.1.6: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.1.6: Glob versions prior to v9 are no longer supported
npm warn deprecated @xmldom/xmldom@0.7.13: this version is no longer supported, please update to at least 0.8.*

  Hello. Let's create a new ①  app...

✔ Name … hello-one


✔ Template › Fullstack - Drizzle, Postgres, Tamagui, Biome

⠦ Creating...


hello-one created!


✔ Package Manager: › yarn

Created empty yarn.lock file

Installing with yarn...

➤ YN0088: A new stable version of Yarn is available: 4.5.3!
➤ YN0088: Upgrade now by running yarn set version 4.5.3

➤ YN0000: · Yarn 4.5.2
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @biomejs/biome@npm:1.9.4, @dotenvx/dotenvx@npm:1.25.1, @faker-js/faker@npm:9.2.0, @tamagui/config@npm:1.117.2, @tamagui/image-next@npm:1.117.2, and 1495 more.
➤ YN0000: └ Completed in 5s 682ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ react is listed by your project with version 18.3.1 (p68d07), which doesn't satisfy what react-native and other dependencies request (18.2.0).
➤ YN0002: │ hello-one@workspace:. doesn't provide @babel/core (pe4cd3), requested by react-native-reanimated.
➤ YN0002: │ hello-one@workspace:. doesn't provide react-dom (p6af87), requested by react-native-web.
➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 943 packages were added to the project (+ 575.04 MiB).
➤ YN0000: └ Completed in 8s 469ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ @biomejs/biome@npm:1.9.4 must be built because it never has been before or the last one failed
➤ YN0007: │ better-sqlite3@npm:11.6.0 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.18.20 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.19.12 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.23.1 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.24.0 must be built because it never has been before or the last one failed
➤ YN0007: │ @swc/core@npm:1.9.3 [08a90] must be built because it never has been before or the last one failed
➤ YN0007: │ @swc/core@npm:1.9.3 [95d96] must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:3.39.0 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.21.5 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 24s 606ms
➤ YN0000: · Done with warnings in 38s 878ms
yarn install completed successfully.

Done! Created a new project under ./hello-one

To run: 

  cd hello-one
  yarn run dev


brandon@Air JavaScript % cd hello-one 
brandon@Air hello-one % yarn run dev

 ERROR  @vxrn/resolve tried to access @vxrn/query-string, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.                             9:25:41 PM

Required package: @vxrn/query-string (via "@vxrn/query-string/package.json")
Required by: @vxrn/resolve@npm:1.1.334 (via /Users/brandon/.yarn/berry/cache/@vxrn-resolve-npm-1.1.334-43e080e26e-10c0.zip/node_modules/@vxrn/resolve/dist/esm/index.mjs)


  
  Required package: @vxrn/query-string (via "@vxrn/query-string/package.json")
  Required by: @vxrn/resolve@npm:1.1.334 (via /Users/brandon/.yarn/berry/cache/@vxrn-resolve-npm-1.1.334-43e080e26e-10c0.zip/node_modules/@vxrn/resolve/dist/esm/index.mjs)
  
  at makeError (.pnp.cjs:25212:34)
  at resolveToUnqualified (.pnp.cjs:26850:21)
  at Object.resolveToUnqualified (.pnp.cjs:27030:26)
  at resolve$1 (.pnp.loader.mjs:2031:31)
  at nextResolve (node:internal/modules/esm/hooks:750:28)
  at Hooks.resolve (node:internal/modules/esm/hooks:238:30)
  at MessagePort.handleMessage (node:internal/modules/esm/worker:199:24)
  at [nodejs.internal.kHybridDispatch] (node:internal/event_target:822:20)
  at exports.emitMessage (node:internal/per_context/messageport:23:28) 



 ERROR  @vxrn/resolve tried to access @vxrn/query-string, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.                             9:25:41 PM

Required package: @vxrn/query-string (via "@vxrn/query-string/package.json")
Required by: @vxrn/resolve@npm:1.1.334 (via /Users/brandon/.yarn/berry/cache/@vxrn-resolve-npm-1.1.334-43e080e26e-10c0.zip/node_modules/@vxrn/resolve/dist/esm/index.mjs)


brandon@Air hello-one % yarn --version
4.5.2
```

I tried again with npm instead of yarn and "Minimal Tamagui" as the template, and didn't have the same problem.

**Comment by natew** [comment]
@brandondrew are you using pnp somehow? It shouldn't be, but maybe you have a global setting?

**Comment by brandondrew** [comment]
I'm pretty sure I'm not.  Besides the fact that I don't recall ever installing it, it does not appear to be available on my laptop:

```shell
brandon@Air ~ % which pnp
pnp not found
```

Do you see something in the original output that implies that `pnp` is involved somehow?

**Comment by zetavg** [comment]
I see there are `.pnp.*` files in the error stack, and suspect the same:

```
  at makeError (.pnp.cjs:25212:34)
  at resolveToUnqualified (.pnp.cjs:26850:21)
  at Object.resolveToUnqualified (.pnp.cjs:27030:26)
  at resolve$1 (.pnp.loader.mjs:2031:31)
```

Can you help double-check if there's an `.yarnrc.yml` file (normally next to `yarn.lock`) that contains `nodeLinker: node-modules`?

**Comment by zetavg** [comment]
Another thing to check is to `ls node_modules/react-native/package.json` and see if that's there.

**Comment by brandondrew** [comment]
There's no `.yarnrc.yml` file anywhere in the project, but `node_modules/react-native/package.json` is there.

**Comment by zetavg** [comment]
Thanks for checking, hmm that's interesting... but can you try adding a `.yarnrc.yml` with the following content and see if it helps?

```yaml
nodeLinker: node-modules
```

**Comment by natew** [comment]
I made some fixes to the create cli so it sets some config, which should avoid pnp
