### ISSUE TITLE
Unable to start `bun run dev`

### ISSUE THREAD

**Issue by SpaghettiC0des** [onejs/one#282]
I created a minimal tamagui boilerplate. 

Unrelated, but I prebuilt the native code and then compiled an iOS dev build. When I start the server, I get this error.

```
node v21.7.3
bun 1.1.38
```

```
$ one dev
 🩹 Patching react
 🩹 Patching whatwg-url-without-unicode
 🩹 Patching @react-native-masked-view/masked-view

 ERROR  Cannot read properties of undefined (reading 'S')                                                                                                                                                   9:45:26 PM

  at node_modules/react-dom/cjs/react-dom-client.development.js:22644:58
  at Object.<anonymous> (node_modules/react-dom/cjs/react-dom-client.development.js:24716:5)
  at Module._compile (node:internal/modules/cjs/loader:1368:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
  at Module.load (node:internal/modules/cjs/loader:1205:32)
  at Module._load (node:internal/modules/cjs/loader:1021:12)
  at Module.require (node:internal/modules/cjs/loader:1230:19)
  at require (node:internal/modules/helpers:179:18)
  at Object.<anonymous> (node_modules/react-dom/client.js:37:20)
  at Module._compile (node:internal/modules/cjs/loader:1368:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
  at Module.load (node:internal/modules/cjs/loader:1205:32)
  at Module._load (node:internal/modules/cjs/loader:1021:12)
  at Module.require (node:internal/modules/cjs/loader:1230:19)
  at require (node:internal/modules/helpers:179:18)
  at Object.<anonymous> (node_modules/react-native-web/dist/cjs/exports/render/index.js:20:15)
  at Module._compile (node:internal/modules/cjs/loader:1368:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
  at Module.load (node:internal/modules/cjs/loader:1205:32)
  at Module._load (node:internal/modules/cjs/loader:1021:12)
  at Module.require (node:internal/modules/cjs/loader:1230:19)
  at require (node:internal/modules/helpers:179:18)
  at Object.<anonymous> (node_modules/react-native-web/dist/cjs/index.js:12:38)
  at Module._compile (node:internal/modules/cjs/loader:1368:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
  at Module.load (node:internal/modules/cjs/loader:1205:32)
  at Module._load (node:internal/modules/cjs/loader:1021:12)
  at Module.require (node:internal/modules/cjs/loader:1230:19)
  at require (node:internal/modules/helpers:179:18)
  at Object.<anonymous> (node_modules/@tamagui/static/dist/registerRequire.js:23:200)
  at Module._compile (node:internal/modules/cjs/loader:1368:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
  at Module.load (node:internal/modules/cjs/loader:1205:32)
  at Module._load (node:internal/modules/cjs/loader:1021:12)
  at Module.require (node:internal/modules/cjs/loader:1230:19)
  at require (node:internal/modules/helpers:179:18)
  at Object.<anonymous> (node_modules/@tamagui/static/dist/extractor/loadTamagui.js:34:321)
  at Module._compile (node:internal/modules/cjs/loader:1368:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
  at Module.load (node:internal/modules/cjs/loader:1205:32)
  at Module._load (node:internal/modules/cjs/loader:1021:12)
  at Module.require (node:internal/modules/cjs/loader:1230:19)
  at require (node:internal/modules/helpers:179:18)
  at Object.<anonymous> (node_modules/@tamagui/static/dist/extractor/createExtractor.js:28:795)
  at Module._compile (node:internal/modules/cjs/loader:1368:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
  at Module.load (node:internal/modules/cjs/loader:1205:32)
  at Module._load (node:internal/modules/cjs/loader:1021:12)
  at Module.require (node:internal/modules/cjs/loader:1230:19)
  at require (node:internal/modules/helpers:179:18)
  at Object.<anonymous> (node_modules/@tamagui/static/dist/exports.js:23:30)
  at Module._compile (node:internal/modules/cjs/loader:1368:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
  at Module.load (node:internal/modules/cjs/loader:1205:32)
  at Module._load (node:internal/modules/cjs/loader:1021:12)
  at Module.require (node:internal/modules/cjs/loader:1230:19)
  at require (node:internal/modules/helpers:179:18)
  at Object.<anonymous> (node_modules/@tamagui/static/dist/index.js:27:23)
  at Module._compile (node:internal/modules/cjs/loader:1368:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
  at Module.load (node:internal/modules/cjs/loader:1205:32)
  at Module._load (node:internal/modules/cjs/loader:1021:12)
  at cjsLoader (node:internal/modules/esm/translators:366:17)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:315:7)
  at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
  at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
  at async importStatic (node_modules/@tamagui/vite-plugin/dist/esm/loadTamagui.mjs:1:35)
  at async getStatic (node_modules/@tamagui/vite-plugin/dist/esm/loadTamagui.mjs:6:51)
  at async loadTamaguiBuildConfig (node_modules/@tamagui/vite-plugin/dist/esm/loadTamagui.mjs:16:20)
  at async load (node_modules/@tamagui/vite-plugin/dist/esm/plugin.mjs:18:34)
  at async config (node_modules/@tamagui/vite-plugin/dist/esm/plugin.mjs:45:11)
  at async runConfigHook (node_modules/vite/dist/node/chunks/dep-BZ_CwQkz.js:68197:19)
  at async resolveConfig (node_modules/vite/dist/node/chunks/dep-BZ_CwQkz.js:67589:12)
  at async _createServer (node_modules/vite/dist/node/chunks/dep-BZ_CwQkz.js:58281:18)
  at async start (node_modules/vxrn/dist/exports/dev.mjs:29:22)
  at async run (node_modules/one/dist/esm/cli/run.mjs:26:9)
  at async Object.run (node_modules/one/dist/esm/cli.mjs:54:7)
  at async runCommand (node_modules/citty/dist/index.mjs:316:16)
  at async runCommand (node_modules/citty/dist/index.mjs:307:11)
  at async runMain (node_modules/citty/dist/index.mjs:445:7)



 ERROR  Cannot read properties of undefined (reading 'S')                                                                                                                                                   9:45:26 PM

error: script "dev" exited with code 1
```

**Comment by sunxyw** [comment]
Same with the `fullstack` template.

**Comment by natew** [comment]
Hm weird, this must have just started

**Comment by natew** [comment]
I'll check here soon, we also are going to move to React 19 exclusively here soon even for native, since we are in beta we want to get onto the most modern libraries before we API stabilize.

**Comment by zetavg** [comment]
Same with `yarn` but a different error:

```
Incompatible React versions: The "react" and "react-dom" packages must have the exact same version. Instead got: - react: 19.0.0-rc-fb9a90fa48-20240614 - react-dom: 19.0.0 Learn more: https://react.dev/warnings/version-mismatch
```

I think it's because the `one` package has:

```
    "react": ">=18.0.0",
    "react-dom": ">=18.0.0",
```

And since React released v19 recently, that'll be resolved to 19.
