### ISSUE TITLE
Initial React Native HMR prints an error

### ISSUE THREAD

**Issue by kraenhansen** [onejs/one#315]
Performing a change to an app running on iOS via the Expo Go app from the minimal template, I see this error on the first change to the index.tsx:

```
✓ built in 2.44s
 ①    ⓵ [hmr] connecting...
 ①    ⓵ [hmr] connected
 ①   [log] Running "main" with {"rootTag":11,"initialProps":{"exp":{"appOwnership":"expo","initialUri":"exp://192.168.1.194:8081/","shell":0,"manifestString":"{\"launchAsset\":{\"key\":\"bundle\",\"contentType\":\"application\\/javascript\",\"url\":\"http:\\/\\/192.168.1.194:8081\\/index.bundle?platform=ios&dev=true&hot=false&transform.engine=hermes&transform.bytecode=true&transform.routerRoot=app\"},\"assets\":[],\"createdAt\":\"2024-12-17T22:24:46.564Z\",\"isVerified\":true,\"metadata\":{},\"runtimeVersion\":\"exposdk:51.0.0\",\"extra\":{\"eas\":{},\"scopeKey\":\"@anonymous\\/hello-world-6c78aead-4a7f-4803-a351-3c3d69c6955c\",\"expoClient\":{\"version\":\"1.1.345-1734464750388\",\"_internal\":{\"packageJsonPath\":\"\\/Users\\/kraen.hansen\\/Repositories\\/hello-world\\/package.json\",\"projectRoot\":\"\\/Users\\/kraen.hansen\\/Repositories\\/hello-world\",\"staticConfigPath\":\"\\/Users\\/kraen.hansen\\/Repositories\\/hello-world\\/app.json\",\"isDebug\":false,\"dynamicConfigPath\":{}},\"ios\":{},\"hostUri\":\"192.168.1.194:8081\",\"plugins\":[\"vxrn\\/expo-plugin\"],\"icon\":\".\\/public\\/app-icon.png\",\"slug\":\"hello-world\",\"splash\":{\"resizeMode\":\"contain\",\"backgroundColor\":\"#000000\",\"image\":\"__vxrn_unstable_internal\\/icon.png\",\"imageUrl\":\"https:\\/\\/github.com\\/user-attachments\\/assets\\/e816c207-e7d2-4c2e-8aa5-0d4cbaa622bf\"},\"platforms\":[\"ios\",\"android\"],\"iconUrl\":\"https:\\/\\/github.com\\/user-attachments\\/assets\\/6894506b-df81-417c-a4cd-9c125c7ba37f\",\"sdkVersion\":\"51.0.0\",\"name\":\"hello-world\"},\"expoGo\":{\"developer\":{\"projectRoot\":\"\\/Users\\/kraen.hansen\\/Repositories\\/hello-world\",\"tool\":\"expo-cli\"},\"__flipperHack\":\"React Native packager is running\",\"mainModuleName\":\"node_modules\\/expo\\/AppEntry\",\"packagerOpts\":{\"dev\":true},\"debuggerHost\":\"192.168.1.194:8081\"}},\"id\":\"6e28f234-0c46-4917-8745-fe96bb52f16f\"}"}}}
 ①   [vite] connected.
11:25:00 PM [vite] (client) hmr update /app/index.tsx
11:25:00 PM [vite] (ssr) page reload app/index.tsx
[vite] program reload
[vite] An error happened during full reload
[vite] cannot find entry point module 'virtual:one-entry'.
Error: [vite] cannot find entry point module 'virtual:one-entry'.
    at fetchModule (file:///Users/kraen.hansen/Repositories/hello-world/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:51161:13)
    at async handleInvoke (file:///Users/kraen.hansen/Repositories/hello-world/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:43945:22)
    at async EventEmitter.listenerForInvokeHandler (file:///Users/kraen.hansen/Repositories/hello-world/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:44018:19)
 ①    ❶ hmr fetching update: http://192.168.1.194:8081/file?file=%2Fapp%2Findex.tsx&t=1734474300716
```

![Screenshot 2024-12-17 at 23 27 18](https://github.com/user-attachments/assets/479f61f3-980e-4689-98de-d52cc01854e4)

Subsequent updates are fine.

**Comment by natew** [comment]
This appears to be a timing issue with the virtual entry module resolution during the first HMR reload on native.

The error `cannot find entry point module 'virtual:one-entry'` happens because on native, Vite's HMR initially looks for the wrong entry point. Native uses `virtual:one-entry-native` while web uses `virtual:one-entry`.

**Workaround**: The error only occurs on the first change and subsequent updates work fine, so you can continue developing normally after the initial error.

This is a known quirk of the native HMR setup and fixing it requires changes to how Vite's native environment handles module resolution during hot reloads.
