### ISSUE TITLE
[Doc] The Getting Started part is outdated in vxrn

### ISSUE THREAD

**Issue by alantoa** [onejs/one#328]
I''m following the official documentation of `vxrn`, trying to create a minimal example, but it is not working. 
Then I realized that this is because the website has not been updated yet. 

It should be `npm create vxrn@latest` or `npx create-vxrn@latest`. 

![CleanShot 2024-12-20 at 19 03 47@2x](https://github.com/user-attachments/assets/8485ea99-d8e1-48a2-9fa4-deb43f9a6994) 

```sh
➜  workspace npx create vxrn@latest

file:///Users/alantoa/.npm/_npx/0ba4002b88dd17fc/node_modules/create/lib/cli/runCli.js:13
        throw new Error(`Could not import ${templateSource}.`, {
              ^

Error: Could not import create-vxrn@latest.
    at runCli (file:///Users/alantoa/.npm/_npx/0ba4002b88dd17fc/node_modules/create/lib/cli/runCli.js:13:15)
    at async file:///Users/alantoa/.npm/_npx/0ba4002b88dd17fc/node_modules/create/bin/index.js:4:20 {
  [cause]: Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'create-vxrn@latest' imported from /Users/alantoa/.npm/_npx/0ba4002b88dd17fc/node_modules/create/lib/cli/runCli.js
      at packageResolve (node:internal/modules/esm/resolve:854:9)
      at moduleResolve (node:internal/modules/esm/resolve:927:18)
      at defaultResolve (node:internal/modules/esm/resolve:1169:11)
      at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:542:12)
      at ModuleLoader.resolve (node:internal/modules/esm/loader:510:25)
      at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)
      at ModuleLoader.import (node:internal/modules/esm/loader:472:34)
      at defaultImportModuleDynamicallyForModule (node:internal/modules/esm/utils:214:31)
      at importModuleDynamicallyCallback (node:internal/modules/esm/utils:253:12)
      at tryImport (file:///Users/alantoa/.npm/_npx/0ba4002b88dd17fc/node_modules/create/lib/cli/runCli.js:43:9) {
    code: 'ERR_MODULE_NOT_FOUND'
  }
}

Node.js v20.18.1
```

**Comment by natew** [comment]
Ah yea, vxrn docs are mostly not updated for a long time, and I think we need to fix it deploying properly again.

**Comment by natew** [comment]
The vxrn documentation site needs to be redeployed. This is a deployment/infrastructure issue rather than a code fix. We'll update this when the docs are refreshed.
