### ISSUE TITLE
React Native 0.76.4 + Expo SDK 52 broke Expo Image and likely other packages

### ISSUE THREAD

**Issue by christianjuth** [onejs/one#350]
I suspect this affects more packages then just `expo-image`.

### Steps to reproduce:
1. Clone [reproduction repo](https://github.com/christianjuth/one-expo-52-image-bug)
2. Run `yarn install`
3. Run `yarn dev`
4. Type `qr` and launch Expo Go on iOS

### I get the following error
```
✓ 604 modules transformed.
x Build failed in 1.87s
 Error building React Native bundle
node_modules/expo/src/winter/runtime.native.ts (6:9): "polyfillGlobal" is not exported by "virtual:rn-internals:react-native/Libraries/Utilities/PolyfillFunctions", imported by "node_modul
es/expo/src/winter/runtime.native.ts".
file: /Users/personal-projects/one-expo-52-bug/node_modules/expo/src/winter/runtime.native.ts:6:9

4: // @ts-ignore: PolyfillFunctions does not have types exported
5: import { polyfillGlobal as installGlobal } from 'react-native/Libraries/Utilities/PolyfillFunctions';
6:
   ^
7: import { installFormDataPatch } from './FormData';
8: // Add a well-known shared symbol that doesn't show up in iteration or inspection

    at getRollupError (file:///Users/personal-projects/one-expo-52-bug/node_modules/rollup/dist/es/shared/parseAst.js:396:41)
    at error (file:///Users/personal-projects/one-expo-52-bug/node_modules/rollup/dist/es/shared/parseAst.js:392:42)
    at Module.error (file:///Users/personal-projects/one-expo-52-bug/node_modules/rollup/dist/es/shared/node-entry.js:15655:16)
    at Module.traceVariable (file:///Users/personal-projects/one-expo-52-bug/node_modules/rollup/dist/es/shared/node-entry.js:16104:29)
    at ModuleScope.findVariable (file:///Users/personal-projects/one-expo-52-bug/node_modules/rollup/dist/es/shared/node-entry.js:13887:39)
    at FunctionScope.findVariable (file:///Users/personal-projects/one-expo-52-bug/node_modules/rollup/dist/es/shared/node-entry.js:5306:38)
    at FunctionBodyScope.findVariable (file:///Users/personal-projects/one-expo-52-bug/node_modules/rollup/dist/es/shared/node-entry.js:5306:38)
    at Identifier.bind (file:///Users/personal-projects/one-expo-52-bug/node_modules/rollup/dist/es/shared/node-entry.js:5089:40)
    at CallExpression.bind (file:///Users/personal-projects/one-expo-52-bug/node_modules/rollup/dist/es/shared/node-entry.js:2676:23)
    at CallExpression.bind (file:///Users/personal-projects/one-expo-52-bug/node_modules/rollup/dist/es/shared/node-entry.js:11313:15)
    at ExpressionStatement.bind (file:///Users/personal-projects/one-expo-52-bug/node_modules/rollup/dist/es/shared/node-entry.js:2676:23)
    at BlockStatement.bind (file:///Users/personal-projects/one-expo-52-bug/node_modules/rollup/dist/es/shared/node-entry.js:2672:28)
    at FunctionDeclaration.bind (file:///Users/personal-projects/one-expo-52-bug/node_modules/rollup/dist/es/shared/node-entry.js:2676:23)
    at Program.bind (file:///Users/personal-projects/one-expo-52-bug/node_modules/rollup/dist/es/shared/node-entry.js:2672:28)
    at Module.bindReferences (file:///Users/personal-projects/one-expo-52-bug/node_modules/rollup/dist/es/shared/node-entry.js:15634:18)
    at Graph.sortModules (file:///Users/personal-projects/one-expo-52-bug/node_modules/rollup/dist/es/shared/node-entry.js:21163:20)
    at Graph.build (file:///Users/personal-projects/one-expo-52-bug/node_modules/rollup/dist/es/shared/node-entry.js:21066:14)
    at async file:///Users/personal-projects/one-expo-52-bug/node_modules/rollup/dist/es/shared/node-entry.js:21754:13
    at async catchUnfinishedHookActions (file:///Users/personal-projects/one-expo-52-bug/node_modules/rollup/dist/es/shared/node-entry.js:21220:16)
    at async rollupInternal (file:///Users/personal-projects/one-expo-52-bug/node_modules/rollup/dist/es/shared/node-entry.js:21749:5)
    at async buildEnvironment (file:///Users/personal-projects/one-expo-52-bug/node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:50850:14)
    at async getReactNativeBundle (file:///Users/personal-projects/one-expo-52-bug/node_modules/vxrn/dist/utils/getReactNativeBundle.mjs:40:19)
    at async file:///Users/personal-projects/one-expo-52-bug/node_modules/vxrn/dist/plugins/reactNativeDevServer.mjs:100:31
    at async handleRNBundle (file:///Users/personal-projects/one-expo-52-bug/node_modules/vxrn/dist/plugins/reactNativeDevServer.mjs:95:26) {
  binding: 'polyfillGlobal',
  code: 'MISSING_EXPORT',
  exporter: 'virtual:rn-internals:react-native/Libraries/Utilities/PolyfillFunctions',
  id: '/Users/personal-projects/one-expo-52-bug/node_modules/expo/src/winter/runtime.native.ts',
  url: 'https://rollupjs.org/troubleshooting/#error-name-is-not-exported-by-module',
  pos: 22,
  loc: {
```

The weird thing is that `react-native/Libraries/Utilities/PolyfillFunctions` does export `polyfillGlobal` but it's a CJS export. React Native seems to mix ESM and CJS so maybe that's the issue?

https://www.unpkg.com/browse/react-native@0.76.4/Libraries/Utilities/PolyfillFunctions.js

**Comment by zetavg** [comment]
Just tested `v1.1.378` with [expo-image's example](https://docs.expo.dev/versions/latest/sdk/image/#usage) and it seems to be working, but there're some errors that I'm not sure if those will break things and still in the progress of fixing.

https://github.com/user-attachments/assets/f057f217-0e44-471d-844d-bcd257ffd1bc
