### ISSUE TITLE
Unable to start dev server when `expo-updates` is configured

### ISSUE THREAD

**Issue by SpaghettiC0des** [onejs/one#351]
1. Create a new `one` project.
1. Run `eas update:configure`
1. Run `bun dev:clean`.

```bash
one dev --clean
[vxrn] cleaning

    ➡ [tamagui] built config and components (152ms)
[vite] connected.
[vite] connected.
Cannot optimize dependency: @expo/cli, present in ssr 'optimizeDeps.include'

 ERROR  Failed to resolve entry for package "expo-structured-headers". The package may have incorrect main/module/exports specified in its package.json.                                6:54:13 PM

    at packageEntryFailure (node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:16462:15)
    at resolvePackageEntry (node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:16459:3)
    at tryNodeResolve (node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:16324:18)
    at ResolveIdContext.resolveId (node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:16109:19)
    at EnvironmentPluginContainer.resolveId (node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:47142:17)
    at async resolve (node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:47683:12)
    at async node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:47699:22
    at async node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:53533:16
```

**Comment by natew** [comment]
Fix in 75dd63a5fb0e5f8db0adf185886d43cc26698307 out in v1.1.376
