### ISSUE TITLE
Trying to get react-native + react-native-web + vite to work together

### ISSUE THREAD

**Issue by vikingprank** [onejs/one#58]
Followed this guide https://vxrn.dev/get-started.html
Ran `npx vxrn dev` and I'm getting all these errors:
```

Failed to resolve dependency: react-native-web-internals, present in client 'optimizeDeps.include'
Failed to resolve dependency: use-latest-callback, present in client 'optimizeDeps.include'
Failed to resolve dependency: @supabase/auth-helpers-react, present in client 'optimizeDeps.include'
Failed to resolve dependency: parse-numeric-range, present in client 'optimizeDeps.include'
Failed to resolve dependency: @docsearch/react, present in client 'optimizeDeps.include'
Failed to resolve dependency: @algolia/autocomplete-core, present in client 'optimizeDeps.include'
Failed to resolve dependency: @algolia/autocomplete-plugin-algolia-insights, present in client 'optimizeDeps.include'
Failed to resolve dependency: @algolia/autocomplete-shared, present in client 'optimizeDeps.include'
Failed to resolve dependency: moti, present in client 'optimizeDeps.include'
Failed to resolve dependency: compare-versions, present in client 'optimizeDeps.include'
Failed to resolve dependency: swr, present in client 'optimizeDeps.include'
Failed to resolve dependency: refractor/lang/tsx, present in client 'optimizeDeps.include'
Failed to resolve dependency: tamagui/linear-gradient, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/linear-gradient, present in client 'optimizeDeps.include'
Failed to resolve dependency: expo-modules-core, present in client 'optimizeDeps.include'
Failed to resolve dependency: expo-status-bar, present in client 'optimizeDeps.include'
Failed to resolve dependency: @floating-ui/react, present in client 'optimizeDeps.include'
Failed to resolve dependency: @floating-ui/react-dom, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/constants, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/react-native-use-responder-events, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/alert-dialog, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/simple-hash, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/use-did-finish-ssr, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/use-event, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/portal, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/compose-refs, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/avatar, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/core, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/dialog, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/group, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/helpers-icon, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/helpers, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/image, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/lucide-icons, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/popover, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/popper, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/scroll-view, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/select, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/sheet, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/switch, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/tabs, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/toast, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/toggle-group, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/tooltip, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/use-window-dimensions, present in client 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/web, present in client 'optimizeDeps.include'
Failed to resolve dependency: tamagui, present in client 'optimizeDeps.include'
Failed to resolve dependency: reforest, present in client 'optimizeDeps.include'
Failed to resolve dependency: react-native-web-internals, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: use-latest-callback, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @supabase/auth-helpers-react, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: parse-numeric-range, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @docsearch/react, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @algolia/autocomplete-core, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @algolia/autocomplete-plugin-algolia-insights, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @algolia/autocomplete-shared, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: moti, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: compare-versions, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: swr, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: refractor/lang/tsx, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: tamagui/linear-gradient, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/linear-gradient, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: expo-modules-core, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: expo-status-bar, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @floating-ui/react, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @floating-ui/react-dom, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/constants, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/react-native-use-responder-events, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/alert-dialog, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/simple-hash, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/use-did-finish-ssr, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/use-event, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/portal, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/compose-refs, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/avatar, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/core, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/dialog, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/group, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/helpers-icon, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/helpers, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/image, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/lucide-icons, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/popover, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/popper, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/scroll-view, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/select, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/sheet, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/switch, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/tabs, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/toast, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/toggle-group, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/tooltip, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/use-window-dimensions, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: @tamagui/web, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: tamagui, present in ssr 'optimizeDeps.include'
Failed to resolve dependency: reforest, present in ssr 'optimizeDeps.include'
✘ [ERROR] Could not resolve "expo-modules-core"

    node_modules/expo-constants/build/Constants.js:1:56:
      1 │ import { CodedError, requireOptionalNativeModule } from 'expo-modules-core';
        ╵                                                         ~~~~~~~~~~~~~~~~~~~

  You can mark the path "expo-modules-core" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "expo-modules-core"

    node_modules/expo-linking/build/Linking.js:1:36:
      1 │ import { UnavailabilityError } from 'expo-modules-core';
        ╵                                     ~~~~~~~~~~~~~~~~~~~

  You can mark the path "expo-modules-core" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "expo-modules-core"

    node_modules/vxs/dist/esm/constants.mjs:1:21:
      1 │ import * as EMC from "expo-modules-core";
        ╵                      ~~~~~~~~~~~~~~~~~~~

  You can mark the path "expo-modules-core" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.


 ERROR  Build failed with 3 errors:                                                                                                                                         12:05:57 AM
node_modules/expo-constants/build/Constants.js:1:56: ERROR: Could not resolve "expo-modules-core"
node_modules/expo-linking/build/Linking.js:1:36: ERROR: Could not resolve "expo-modules-core"
node_modules/vxs/dist/esm/constants.mjs:1:21: ERROR: Could not resolve "expo-modules-core"

  node_modules/expo-constants/build/Constants.js:1:56: ERROR: Could not resolve "expo-modules-core"
  node_modules/expo-linking/build/Linking.js:1:36: ERROR: Could not resolve "expo-modules-core"
  node_modules/vxs/dist/esm/constants.mjs:1:21: ERROR: Could not resolve "expo-modules-core"
  at failureErrorWithLog (node_modules/vite/node_modules/esbuild/lib/main.js:1651:15)
  at node_modules/vite/node_modules/esbuild/lib/main.js:1059:25
  at node_modules/vite/node_modules/esbuild/lib/main.js:1527:9
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 



 ERROR  Build failed with 3 errors:                                                                                                                                         12:05:57 AM
node_modules/expo-constants/build/Constants.js:1:56: ERROR: Could not resolve "expo-modules-core"
node_modules/expo-linking/build/Linking.js:1:36: ERROR: Could not resolve "expo-modules-core"
node_modules/vxs/dist/esm/constants.mjs:1:21: ERROR: Could not resolve "expo-modules-core"
```

I'm not using expo, any pointers to what I should be doing to solve these errors?
Cheers

**Comment by natew** [comment]
Yea it’s broken atm as we’re migrating to react 19 and implementing many things. Should have a proper beta in a few weeks tops.
